Dockerfile
We need to set io.openshift.release.operator true label for all images that go in release
=> Label gcp provider image

.ci-operator.yaml, Dockerfile.rhel, pkg/cloud/gcp/actuators/machine/reconciler_test.go, pkg/cloud/gcp/actuators/util/gcp_credentials.go
Cherry-picked from #18 
Apply go fmt in follow up commit
=> Updating ose-machine-api-provider-gcp images to be consistent with ART

pkg/cloud/gcp/actuators/machine/reconciler.go, pkg/cloud/gcp/actuators/machine/reconciler_test.go, pkg/cloud/gcp/actuators/services/compute/computeservice.go, pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
Control plane machines on GCP need to be in instance group for the internal load balancer to work. This PR automatically assigns the instance to an already created instance group when it is being updated and removes it from instance group when it is being deleted.
=> OCPCLOUD-1755: Register control plane machines to instance group

pkg/cloud/gcp/actuators/machine/reconciler.go, pkg/cloud/gcp/actuators/machine/reconciler_test.go
to be more thorough about checking for empty string and preemptible instances. previously this function only checked if the value was equal to "Always". but, this misses the default omission case where we should be defaulting to always restart but weren't. additionally, when the instance is preemptible it is not possible to set a restart policy of always.
=> OCPBUGS-1557: refactor restartPolicyToBool function

cmd/manager/main.go
On other providers we set the sync period to 10 minutes down from the default of 10 hours. This means we pick up changes within the cloud provider in a reasonable time frame.
For example, if a user adds an external IP address manually, this should be picked up so that CSRs for the serving certificates are approved in a timely manner, this isn't working well with the default sync period.
10 minutes is used in other providers such as AWS and Azure.
=> OCPBUGS-860: Set sync period for Machine controller

pkg/cloud/gcp/actuators/machine/reconciler.go, pkg/cloud/gcp/actuators/machine/reconciler_test.go
this is a cherry-pick of #21 
to be more thorough about checking for empty string and preemptible instances. previously this function only checked if the value was equal to "Always". but, this misses the default omission case where we should be defaulting to always restart but weren't. additionally, errors have been added when the policy is not recognized or the user attempts to set an always restart policy for a preemptible instance.
=> [release-4.12] OCPBUGS-4504: refactor restartPolicyToBool function

pkg/cloud/gcp/actuators/machine/reconciler.go, pkg/cloud/gcp/actuators/machine/reconciler_test.go, pkg/cloud/gcp/actuators/services/compute/computeservice.go, pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
This PR solves a bug, where machines were stuck in add/delete phase when removing a failure domain from CPMS.
Whenever we encounter an instance group that is unknown to us, we register it.
Edit: Have to add that new instance group to load balancer.
=> OCPBUGS-3904: Register unknown instance groups

pkg/cloud/gcp/actuators/machine/reconciler.go, pkg/cloud/gcp/actuators/machine/reconciler_test.go
this is a cherry-pick of #21 
to be more thorough about checking for empty string and preemptible instances. previously this function only checked if the value was equal to "Always". but, this misses the default omission case where we should be defaulting to always restart but weren't. additionally, errors have been added when the policy is not recognized or the user attempts to set an always restart policy for a preemptible instance.
fixes OCPBUGS-4579
=> [release-4.11] OCPBUGS-4579: refactor restartPolicyToBool function

pkg/cloud/gcp/actuators/machine/reconciler.go, pkg/cloud/gcp/actuators/machine/reconciler_test.go, pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
New machine is stuck in `Provisioning` when we delete one of the zones from CPMS on GCP :  "The resource `<path-to-network-resource>` not found".
Edit: This got tested pre-merged by QE.
=> OCPBUGS-7366: New machine stuck in provisioning on VPC

pkg/cloud/gcp/actuators/machine/reconciler.go
This PR removes the full error from the Reason field in RegisterFailedInstanceXXXX metrics, because it was causing the metric to have high/unbound cardinality. The full error is still logged, so this PR should not affect the ability to troubleshoot issues.
=> OCPBUGS-11223: Reduce metrics cardinality.

pkg/termination/termination_test.go
This change moves the bad url test to its own `Context` block so that it does not get caught in the mock termination service counter. In some cases it is possible for the bad url test to be run first, when this happens the counter will never advance because the url is not valid. This produces a dead lock condition in the test. Migrating the test to its own block alleviates this issue.
This change also updates the "not fulfilled" test to ensure that the counter is updated when the http handler is replaced.
=> OCPBUGS-20267: update bad url endpoint termination handler test

pkg/cloud/gcp/actuators/machineset/controller.go, pkg/cloud/gcp/actuators/machineset/controller_test.go, pkg/cloud/gcp/actuators/util/gcp_machine_architecture.go, pkg/cloud/gcp/actuators/util/gcp_machine_architecture_test.go
This PR adds a facility to support arch-aware autoscale from zero in multiarch compute clusters.
Since the gcloud API does not provide the architecture information from a give machine type, we define a map of pairs `(prefix, architecture)`. If a known pair is available, the labels' capacity annotation is set to the appropriate architecture. Otherwise, the capacity labels annotation will set to `kubernetes.io/arch=amd64`
Today, GCP provides `arm64` machine types with the `t2a-` prefix. The drawback of this implementation is the need to maintain the map in future when new machine types could be added.
cc @Prashanth684
I'm not sure this path can be viable. I found other code in this actuator that leverages checks on the machine type prefixes to perform some actions (for example, …
=> MIXEDARCH-258: Set the capacity annotation for arch-aware autoscale from zero

pkg/termination/termination.go, pkg/termination/termination_test.go
This change adds an extra check the termination handler so that it can try one more time after having the context cancelled.  It is needed to fix a race condition where the termination signal can be missed and the machine is not properly marked for removal.
This change also fixes a few deprecated calls in the termination handler.
=> OCPBUGS-2117: Add extra check to termination handler

pkg/cloud/gcp/actuators/util/gcp_machine_architecture.go
** The c4a instance type needs to be added for other projects that import this package and its validation. Added the c4a instance type as an ARM type to the dictionary for lookup.
=> CORS-3739: Add c4a instance as arm type

pkg/cloud/gcp/actuators/machine/reconciler.go, pkg/cloud/gcp/actuators/services/compute/computeservice.go, pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
this change updates the way that a2 instance types are validated for quota. gcp has added a new type of a2 instance category named "ultragpu". the ultragpu series has a different type of gpu, "nvidia-a100-80gb", which requires a new constant be applied to the quota.
to make this workflow more modular in the future, it is also being adjusted to dynamically discover the gpu type during the instance quota validation.
=> OCPBUGS-45923: update a2 gpu detection logic to be dynamic

pkg/cloud/gcp/actuators/machine/reconciler.go, pkg/cloud/gcp/actuators/services/compute/computeservice.go, pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
this change updates the way that a2 instance types are validated for quota. gcp has added a new type of a2 instance category named "ultragpu". the ultragpu series has a different type of gpu, "nvidia-a100-80gb", which requires a new constant be applied to the quota.
to make this workflow more modular in the future, it is also being adjusted to dynamically discover the gpu type during the instance quota validation.
=> [release-4.17] OCPBUGS-46082: update a2 gpu detection logic to be dynamic

pkg/cloud/gcp/actuators/machine/reconciler.go
GCP started responding with 400 for invalid zone instead of 404. This PR updates the exits() to handle the change.
It also removes the zone get API call and instead determines invalid zone or projectID from the error message of the instance get call.
=> OCPBUGS-43531: Refactor exists() to handle gcp API change

pkg/cloud/gcp/actuators/machine/reconciler.go, pkg/cloud/gcp/actuators/services/compute/computeservice.go
this change expands the quota detection logic to include a3 instance types in addition to a2.
=> OCPBUGS-46387: add a3 instance types to gpu quota validation logic

cmd/manager/main.go, pkg/cloud/gcp/actuators/machine/actuator.go, pkg/cloud/gcp/actuators/machine/actuator_test.go, pkg/cloud/gcp/actuators/machine/machine_scope.go, pkg/cloud/gcp/actuators/machine/machine_scope_test.go, pkg/cloud/gcp/actuators/machineset/controller.go, pkg/cloud/gcp/actuators/services/compute/computeservice.go, pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go, pkg/cloud/gcp/actuators/services/tags/tagservice.go, pkg/cloud/gcp/actuators/services/tags/tagservice_mock.go, pkg/cloud/gcp/actuators/util/gcp_endpoints.go, pkg/cloud/gcp/actuators/util/gcp_endpoints_mock.go
** Vendor update. Update openshift/api to use a version that contains the custom endpoint information.
** When creating the compute service, determine if there is a custom endpoint set in the infrastructure platform status.
** When creating the tagging service, determine fi there is a custom endpoint set in the infrastructure platform status.
** Add a function template to pass to the actuator and machine scope parameters for looking up the custom endpoints. During tests a Mock function is passed that will do nothing and return no error. During the actual execution the real lookup function is passed. When no function is set the default will be to use the function that will look through the infrastructure to find the custom endpoints.
** Update machine scope tests to set a mock function.
** …
=> CORS-3906: Update MAPI GCP Provider to use custom GCP endpoints

pkg/cloud/gcp/actuators/machine/reconciler.go, pkg/cloud/gcp/actuators/machine/reconciler_test.go, pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
this change relaxes some of the quota checking logic so that if a
specific metric is not detecting in the list of quotas for a region, the
controller will emit a log warning but allow the creation of the
instance.
this is being introduced to help solve issues where the google apis do
not return regional information for some attached gpus, such as
NVIDIA_H100_GPU.
=> OCPBUGS-46387: allow instances with unknown quotas to be created

go.mod, go.sum, pkg/cloud/gcp/actuators/machine/actuator_test.go, pkg/cloud/gcp/actuators/machine/reconciler.go, pkg/cloud/gcp/actuators/machine/reconciler_test.go, pkg/cloud/gcp/actuators/machineset/controller.go, pkg/cloud/gcp/actuators/machineset/controller_test.go, pkg/cloud/gcp/actuators/services/compute/computeservice.go, pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go, pkg/cloud/gcp/actuators/util/gcp_uefi_disk_check.go, pkg/cloud/gcp/actuators/util/gcp_uefi_disk_check_test.go, pkg/cloud/gcp/actuators/util/register.go, pkg/cloud/gcp/actuators/util/util_suite_test.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/LICENSE, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/config/v1/cluster_operator.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/config/v1/infrastructure.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/consts.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/interfaces.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/aws_provider_spec.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/azure_provider_spec.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/gcp_provider_spec.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/machine.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/machineset.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/openstack_provider_spec.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/vsphere_provider_spec.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/metadata.go, vendor/modules.txt
Manual cherry-pick of https://github.com/openshift/machine-api-provider-gcp/pull/108
It also relies on: https://github.com/openshift/machine-api-operator/pull/1355 and https://github.com/openshift/cluster-api-actuator-pkg/pull/404
=> [release-4.16] OCPBUGS-55249: Disable shielded VMs for non-UEFI disks

cmd/manager/main.go
This enables us to configure concurrent reconciliation of the machines to speed up processing of machines during large scale up events.
This matches a performance improvement we made on Azure previously.
=> OCPBUGS-59376: Add max-concurrent-reconciles flag to machine actuator
